version: "3"

services:
  server:
    build: ./server
    ports:
      - "3001:3001"
    env_file:
      - ./server/.env  # ✅ Load MongoDB URI from this file

  client:
    build: ./client
    ports:
      - "5173:5173"
    depends_on:
      - server
    environment:
      - VITE_API_URL=http://localhost:3001  # ✅ Use localhost instead of server
